name: audio_analysis_for_n00bz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - scipy=1.7.1
  - librosa=0.8.1
  - pip:
    - requests==2.26
    - tqdm==4.62.3
    - mingus==0.6.1
    - youtube-dl==2021.12.1
    - pygame==2.1.2
    - music21==7.1.0