name: book_scanner_to_audiobook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - opencv=4.5.3
  - scipy=1.7.1
  - pip:
    - requests==2.26
    - beautifulsoup4==4.10.0
    - tqdm==4.62.3