name: book_scanner_to_audiobook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - opencv=4.5.3
  - scipy=1.7.1
  - librosa=0.8.1
  - pip:
    - requests==2.26
    - beautifulsoup4==4.10.0
    - tqdm==4.62.3
    - boto3==1.20.28
    - amazon-textract-response-parser==0.1.23
    - azure-cognitiveservices-vision-computervision==0.9.0
    - azure-cognitiveservices-speech==1.19.0
    - amazon-textract-response-parser==0.1.23
    - editdistance==0.6.0
    - jiwer==2.3.0