name: kalshi_prediction_market
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - altair=4.2.0
  - pip:
    - requests==2.27.1
    - beautifulsoup4==4.11.1
    - tqdm==4.62.3