name: menu_spider_scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - poppler=22.04.0
  - scrapy=2.6.1
  - opencv=4.5.5
  - cmake=3.22.1
  - pkg-config=0.29.2
  - shapely=1.7.1
  - pip:
    - requests==2.27.1
    - beautifulsoup4==4.11.1
    - tqdm==4.62.3
    - python-poppler==0.3.0